# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m8kjAarMelHQV8g0uFZc2u9mzy9U_YLt
"""

import pandas as pd
import numpy as np

df=pd.read_csv("/content/amazon_sales_data.csv")

df.head()

df.dtypes

df.isnull().sum()

df["Customer Name"] = df["Customer Name"].fillna("Unknown")
df["Gender"] = df["Gender"].fillna("Unknown")
df["Country"] = df["Country"].fillna("Unknown")

"""Filling text columns with unknown as we cant drop data"""

df["Quantity"] = df["Quantity"].fillna(1)
df["Price"] = df["Price"].fillna(df["Price"].mean())
df["Total"] = df["Quantity"] * df["Price"]

"""filling unknown quantity as 1 and price with avg price

"""

df.isnull().sum()

df.drop_duplicates()

df["Gender"] = df["Gender"].str.strip().str.lower()
df["Product"] = df["Product"].str.title().str.strip()
df["Category"] = df["Category"].str.title().str.strip()
df["Country"] = df["Country"].str.strip().str.lower()
df["Category"] = df["Category"].str.title().str.strip()

"""removing white spaces and making all the values standard"""

df["Country"] = df["Country"].replace({
    "usa": "USA",
    "u.s.a": "USA",
    "united states": "USA",
    "united kingdom": "UK",
    "uk": "UK",
    "canada": "Canada",
    "india": "India"
})

df["Gender"] = df["Gender"].replace({
    "female": "Female",
    "male": "Male",
    "f": "Female",
    "m": "Male",
    None: "Unknown",
    "": "Unknown"
})

"""handling inconsistent values"""

df["Order Date"] = pd.to_datetime(df["Order Date"], dayfirst=True, errors="coerce")
df["Order Date"] = df["Order Date"].dt.strftime('%d-%m-%Y')

"""converting the data type to date-time format."""

df.head()